# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160530_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=b'documents'),
        ),
    ]
